#include "sandbox_plugin.h"
#include "spin_plugin.h"
#include "core/engine.h"
#include "core/world.h"
#include "base/log.h"
#include "core/components/mesh_component.h"
#include "core/components/camera_component.h"

#include "core/meta/registration.h"

const char* scene_str = "{\n"
                        "    \"__guid\": \"3b0f279e212a4a19b701ef9a004083c4\",\n"
                        "    \"__type\": \"entity\",\n"
                        "    \"children\": [\n"
                        "        {\n"
                        "            \"__guid\": \"9842a18a80934495b4ef131a41cd783b\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"ad2f330108734c3796091e949a5e3987\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"052e1bc387f24ff38c61111c3534979f\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"3ff64d0796c8404c8f24dcd649530f38\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"719f9dab3a10474393496ab984de753a\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 0.699999988079071,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 3.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"0904fd5b4e0741c1baebc56a9ef6d496\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"ac573f06c1074f5eaddcfaee0566562f\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"f33976e154af4ef89980563b64f25a6b\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -0.699999988079071,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 3.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"18b94633905449739c7b68642c753f3b\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"9c67baf587df4f8ea2b6f1de541321e9\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"c53fc64413d54b3887f1c6a77446d85d\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"f4090cb013dd46168780d8f9a2622a2e\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 1.399999976158142,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 5.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"74758251eda246b097efa205196ccbf7\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"e3ba77d13ecb4b2180e819d003c817df\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"62daa7b57d96445c8158bcae3de166ff\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -1.399999976158142,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 5.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"b2c21a1496b24e698340d982095e0de2\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"51d95565dcec49fe97d0b2a1d6ccf41a\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"4a206da3edc641eab7d364a17fcc31a8\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"b98375195efa468c85bbede933e0c47e\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 2.0999999046325684,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 7.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"e85d03ac596f4b6894a8451e729d374c\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"41834d2bdd124b6e902987efafaf9faf\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"3687c4b6143b4b01869b5b516699c0b9\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -2.0999999046325684,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 7.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"c1b8e5f635d749b59cd6275283c2b209\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"f1dc0375710b4d6ba9967fd624d1bb87\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"5df157ee73e74197929ab6c428b0776b\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"e26e453b2e6f41c9a8553e5e98ad9c65\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 2.799999952316284,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 9.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"f526aa94c6a54073ac73312f8137b5eb\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"68133392ff1e4db2b9bfe62877666ce9\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"56769d9ff90b45eb9722356b9673c41a\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -2.799999952316284,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 9.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"ad281a24cea64c28ac8b926743d9670d\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"7dc8c7bfc8734cbf8172bda46b26301b\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"45e08587c0d144e492442e22498343e6\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"2ea88ef42a4742d9bde7c2bfc48ae1d9\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 3.5,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 11.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"5f716912b6f64f16a2849a4670153ae5\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"fe4d5da82422487aa6c79d9550c2f6be\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"0ba3f8f6e78d412da421c7199cc47f79\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -3.5,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 11.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"56baafd3e4874d67af5c4d224542159d\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"25af98d5d556485aace1a9c91694c900\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"9179e3698c724e199947e4b0312609f0\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"5888debb24334f89b3d5e2b4cc8d8a71\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 4.199999809265137,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 13.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"8f8d4326293948c1ba79e77abb64a6d1\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"71224c63fd884028b327679453ae7c1c\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"adfc5d48ff2648bf8b3073fb979915c9\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -4.199999809265137,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 13.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"5411302664d94e1583f3f7809ba557a4\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"38ebb3eef35744ba92a2570dc5709947\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"33dc1b9098784814b0d743ae2000e8eb\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"0727d57a2aa9405e9e5f073340d1593d\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 4.900000095367432,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 15.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"bccf44e391f74a998d8032643afc1351\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"8477cb2b6bd044d1802153e8c5550baf\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"293d8d3815f24cacac53243a78bf6b2a\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -4.900000095367432,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 15.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"ea703609c3594b9294cd1146bbeccee3\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"c3ce3e4a329143a6ba13de72433cf9f1\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"91e554e37e54417285d5a380928d1bea\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"41f2943c8bd941cfb8dad31a8b473e6d\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 5.599999904632568,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 17.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"f717370f7ee3491bb4c3e5a6b2a67f22\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"1fb91e1f84c64d5f8315ea374d0f865f\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"785df50ff5044214a35cc6f0bf2edc82\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -5.599999904632568,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 17.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"e9feadf0fce043cda549f0eb6d74148e\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"c3e0193002e748088ba31dbb424e30f3\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"2db6d9c28bf94ed495f5792ef94de12b\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"61a6091c812e4b0784c0368d05e655df\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": 6.299999713897705,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 19.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"ed345271456b4442900d29481ff3e64f\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        },\n"
                        "        {\n"
                        "            \"__guid\": \"fcdb97d336ba49c6b03c62b57ee595d8\",\n"
                        "            \"__type\": \"entity\",\n"
                        "            \"components\": [\n"
                        "                {\n"
                        "                    \"__guid\": \"41073d7347db45dcbad82ea91dd663d5\",\n"
                        "                    \"__type\": \"transform_component\",\n"
                        "                    \"position\": {\n"
                        "                        \"x\": -6.299999713897705,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 19.0\n"
                        "                    },\n"
                        "                    \"rotation\": {\n"
                        "                        \"w\": 1.0,\n"
                        "                        \"x\": 0.0,\n"
                        "                        \"y\": 0.0,\n"
                        "                        \"z\": 0.0\n"
                        "                    },\n"
                        "                    \"scale\": {\n"
                        "                        \"x\": 1.0,\n"
                        "                        \"y\": 1.0,\n"
                        "                        \"z\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"8ad4c91ae29e461597f59e9ff09f77ae\",\n"
                        "                    \"__type\": \"mesh_component\",\n"
                        "                    \"color\": {\n"
                        "                        \"a\": 1.0,\n"
                        "                        \"b\": 1.0,\n"
                        "                        \"g\": 1.0,\n"
                        "                        \"r\": 1.0\n"
                        "                    }\n"
                        "                },\n"
                        "                {\n"
                        "                    \"__guid\": \"39f3500530aa439daf4346def1afb842\",\n"
                        "                    \"__type\": \"custom_component\",\n"
                        "                    \"a\": 42,\n"
                        "                    \"b\": 0.0,\n"
                        "                    \"c\": {\n"
                        "                        \"a\": 0.0\n"
                        "                    }\n"
                        "                }\n"
                        "            ]\n"
                        "        }\n"
                        "    ],\n"
                        "    \"components\": [\n"
                        "        {\n"
                        "            \"__guid\": \"17af790d085540cfb3b1d4a04e931e06\",\n"
                        "            \"__type\": \"transform_component\",\n"
                        "            \"position\": {\n"
                        "                \"x\": 0.0,\n"
                        "                \"y\": 0.0,\n"
                        "                \"z\": 0.0\n"
                        "            },\n"
                        "            \"rotation\": {\n"
                        "                \"w\": 1.0,\n"
                        "                \"x\": 0.0,\n"
                        "                \"y\": 0.0,\n"
                        "                \"z\": 0.0\n"
                        "            },\n"
                        "            \"scale\": {\n"
                        "                \"x\": 1.0,\n"
                        "                \"y\": 1.0,\n"
                        "                \"z\": 1.0\n"
                        "            }\n"
                        "        }\n"
                        "    ]\n"
                        "}";

class test : public plugin_base {
 public:
  int count = 0;
  void stop(engine *e) override {}
  void start(engine *e) override {
    logger::core::Info("test::start");

//    asset scene_asset = asset::parse(scene_str);
//    e->world->create_entity_from_asset(scene_asset);

    auto root_ent = e->world->create_entity();
    auto& ent0_tr = e->world->component<transform_component>(root_ent);

    auto mesh_ent = e->world->create_entity({}, root_ent);
    auto cam_ent = e->world->create_entity({});

    e->world->add_component<mesh_component>(mesh_ent);

    for (int i = 1; i < 10; i++) {
      {
        vec3 pos = (i * 2.0f + 1) * vec3::forward() + (i * 0.7f) * vec3::right();
        auto ent = e->world->create_entity({}, root_ent);
        e->world->add_component<mesh_component>(ent);
        e->world->set_local_transform(ent, transform::from_matrix(mat4::translation(pos)));
      }
      {
        vec3 pos = (i * 2.0f + 1) * vec3::forward() + (i * 0.7f) * -vec3::right();
        auto ent = e->world->create_entity({}, root_ent);
        e->world->add_component<mesh_component>(ent);
        e->world->set_local_transform(ent, transform::from_matrix(mat4::translation(pos)));
        e->world->add_component<custom_component>(ent).a = 42;
      }
    }

    auto& cam = e->world->add_component<camera_component>(cam_ent);
    e->world->set_local_transform(cam_ent, transform::from_matrix(mat4::translation({0,-2.0f,-3.0f})));
  }

  void update(engine *e) override {
    auto mesh_view = e->world->view<mesh_component, custom_component>();
    for (ecs::entity id : mesh_view) {
      mesh_view.get<mesh_component>(id).set_color(color::blue());
    }
  }
};


void load_sandbox_plugin(engine* engine) {

  register_type(custom_component);

  logger::core::Info("load_sandbox_plugin");
  engine->plugins->add_plugin<test>("test");

}


void unload_sandbox_plugin(engine* engine) {

  logger::core::Info("unload_sandbox_plugin");
  engine->plugins->remove_plugin("test");

}

void serialization<custom_component>::from_asset(const asset &asset, custom_component *comp) {
  comp->a = asset["a"];
  comp->b = asset["b"];
  comp->c.a = asset["c"]["a"];
}

void serialization<custom_component>::to_asset(asset &asset, const custom_component *comp) {
  asset["a"] = comp->a;
  asset["b"] = comp->b;
  asset["c"]["a"] = comp->c.a;
}